-- TEST FIXTURE: validación integral de gráficas automáticas.
-- 100 % ficticio, identificadores TEST-AUTO-*, sin eliminar ni modificar datos existentes.
PRAGMA foreign_keys = ON;
--> statement-breakpoint
INSERT OR IGNORE INTO `personnel_profiles` (`id`,`full_name`,`role`,`site`,`internal_code`,`date_of_birth`,`diagnosis`,`address`,`phone`,`guardian_name`,`guardian_phone`,`preferred_language`,`emergency_contact`,`custom_fields`,`notes`,`status`) VALUES
('TEST-AUTO-GRAPH-CLIENT-001','TEST-AUTO-GRAPH-CLIENT-001','Niño','León','TEST-AUTO-001','2015-01-15','TEST-DIAGNOSTICO-FICTICIO','TEST-DIRECCION-FICTICIA','0000-TEST-AUTO','TEST-CUIDADOR-AUTO','0000-GUARD-AUTO','Español','TEST-EMERGENCIA-AUTO','[{"id":"TEST-AUTO-FIELD-001","label":"Uso","value":"PRUEBA SINTÉTICA DE GRÁFICAS"}]','TEST: perfil ficticio exclusivo para validar gráficas automáticas. No usar clínicamente.','active');
--> statement-breakpoint
INSERT OR IGNORE INTO `intervention_programs` (`id`,`profile_id`,`linked_cycle_id`,`name`,`participant_name`,`site`,`objective`,`instructions`,`status`) VALUES
('TEST-AUTO-PROGRAM-ESCAPE-001','TEST-AUTO-GRAPH-CLIENT-001',NULL,'TEST-AUTO · Conducta de escape','TEST-AUTO-GRAPH-CLIENT-001','León','TEST: reducir de forma sintética la frecuencia de episodios de escape.','TEST: datos ficticios para validar línea, barras, acumulativa, varias series y fases.','active'),
('TEST-AUTO-PROGRAM-FCT-001','TEST-AUTO-GRAPH-CLIENT-001',NULL,'TEST-AUTO · Comunicación funcional','TEST-AUTO-GRAPH-CLIENT-001','León','TEST: aumentar de forma sintética el porcentaje de solicitudes independientes.','TEST: datos ficticios para validar porcentaje, varias series, faltantes y actualización automática.','active');
--> statement-breakpoint
INSERT OR IGNORE INTO `intervention_targets` (`id`,`program_id`,`code`,`name`,`specific_objective`,`measurement`,`unit_label`,`state`,`criteria`,`sort_order`) VALUES
('TEST-AUTO-TARGET-ESCAPE-001','TEST-AUTO-PROGRAM-ESCAPE-001','ESC-01','Episodios de escape','TEST: registrar frecuencia sintética por sesión.','frequency','episodios','acquisition','{"baseline":{"comparator":"lte","threshold":8,"consecutiveSessions":4,"minOpportunities":1,"distinctContexts":1},"acquisition":{"comparator":"lte","threshold":4,"consecutiveSessions":3,"minOpportunities":1,"distinctContexts":1},"mastered":{"comparator":"lte","threshold":2,"consecutiveSessions":3,"minOpportunities":1,"distinctContexts":2},"generalized":{"comparator":"lte","threshold":1,"consecutiveSessions":3,"minOpportunities":1,"distinctContexts":2}}',0),
('TEST-AUTO-TARGET-BREAK-001','TEST-AUTO-PROGRAM-ESCAPE-001','ESC-02','Solicitudes de descanso','TEST: registrar frecuencia sintética de conducta alternativa.','frequency','solicitudes','acquisition','{"baseline":{"comparator":"gte","threshold":3,"consecutiveSessions":4,"minOpportunities":1,"distinctContexts":1},"acquisition":{"comparator":"gte","threshold":7,"consecutiveSessions":3,"minOpportunities":1,"distinctContexts":1},"mastered":{"comparator":"gte","threshold":9,"consecutiveSessions":3,"minOpportunities":1,"distinctContexts":2},"generalized":{"comparator":"gte","threshold":10,"consecutiveSessions":3,"minOpportunities":1,"distinctContexts":2}}',1),
('TEST-AUTO-TARGET-FCT-IND-001','TEST-AUTO-PROGRAM-FCT-001','FCT-01','Solicitud independiente','TEST: porcentaje sintético de oportunidades independientes.','percentage','%','acquisition','{"baseline":{"comparator":"gte","threshold":40,"consecutiveSessions":4,"minOpportunities":5,"distinctContexts":1},"acquisition":{"comparator":"gte","threshold":80,"consecutiveSessions":3,"minOpportunities":5,"distinctContexts":1},"mastered":{"comparator":"gte","threshold":90,"consecutiveSessions":3,"minOpportunities":5,"distinctContexts":2},"generalized":{"comparator":"gte","threshold":90,"consecutiveSessions":3,"minOpportunities":5,"distinctContexts":2}}',0),
('TEST-AUTO-TARGET-FCT-PROMPT-001','TEST-AUTO-PROGRAM-FCT-001','FCT-02','Solicitud con ayuda','TEST: porcentaje sintético de oportunidades con ayuda.','percentage','%','acquisition','{"baseline":{"comparator":"lte","threshold":70,"consecutiveSessions":4,"minOpportunities":5,"distinctContexts":1},"acquisition":{"comparator":"lte","threshold":30,"consecutiveSessions":3,"minOpportunities":5,"distinctContexts":1},"mastered":{"comparator":"lte","threshold":15,"consecutiveSessions":3,"minOpportunities":5,"distinctContexts":2},"generalized":{"comparator":"lte","threshold":10,"consecutiveSessions":3,"minOpportunities":5,"distinctContexts":2}}',1);
--> statement-breakpoint
INSERT OR IGNORE INTO `intervention_sessions` (`id`,`program_id`,`session_date`,`context`,`notes`,`status`,`results`,`transitions`,`closed_at`) VALUES
('TEST-AUTO-SESSION-ESC-001','TEST-AUTO-PROGRAM-ESCAPE-001','2026-05-04','TEST-Centro','TEST: sesión ficticia 1.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":12,"opportunities":20,"note":"TEST-LB","stateAtSession":"baseline"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":1,"opportunities":20,"note":"TEST-LB","stateAtSession":"baseline"}]','[]','2026-05-04T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-002','TEST-AUTO-PROGRAM-ESCAPE-001','2026-05-08','TEST-Escuela','TEST: sesión ficticia 2.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":11,"opportunities":18,"note":"TEST-LB","stateAtSession":"baseline"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":1,"opportunities":18,"note":"TEST-LB","stateAtSession":"baseline"}]','[]','2026-05-08T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-003','TEST-AUTO-PROGRAM-ESCAPE-001','2026-05-12','TEST-Casa','TEST: sesión ficticia 3.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":13,"opportunities":22,"note":"TEST-LB variabilidad","stateAtSession":"baseline"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":2,"opportunities":22,"note":"TEST-LB","stateAtSession":"baseline"}]','[]','2026-05-12T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-004','TEST-AUTO-PROGRAM-ESCAPE-001','2026-05-16','TEST-Centro','TEST: sesión ficticia 4.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":10,"opportunities":19,"note":"TEST-LB","stateAtSession":"baseline"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":2,"opportunities":19,"note":"TEST-LB","stateAtSession":"baseline"}]','[]','2026-05-16T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-005','TEST-AUTO-PROGRAM-ESCAPE-001','2026-05-23','TEST-Escuela','TEST: inicio ficticio de intervención.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":9,"opportunities":20,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":false,"value":null,"opportunities":0,"note":"TEST-No muestreado","stateAtSession":"acquisition"}]','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","code":"ESC-01","targetName":"Episodios de escape","from":"baseline","to":"acquisition","reason":"TEST: cambio sintético de fase"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","code":"ESC-02","targetName":"Solicitudes de descanso","from":"baseline","to":"acquisition","reason":"TEST: cambio sintético de fase"}]','2026-05-23T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-006','TEST-AUTO-PROGRAM-ESCAPE-001','2026-05-27','TEST-Casa','TEST: sesión ficticia 6.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":8,"opportunities":20,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":4,"opportunities":20,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-05-27T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-007','TEST-AUTO-PROGRAM-ESCAPE-001','2026-06-02','TEST-Centro','TEST: sesión ficticia 7.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":7,"opportunities":18,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":5,"opportunities":18,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-02T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-008','TEST-AUTO-PROGRAM-ESCAPE-001','2026-06-07','TEST-Escuela','TEST: sesión ficticia 8.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":7,"opportunities":20,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":6,"opportunities":20,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-07T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-009','TEST-AUTO-PROGRAM-ESCAPE-001','2026-06-14','TEST-Casa','TEST: sesión ficticia 9.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":5,"opportunities":21,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":7,"opportunities":21,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-14T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-010','TEST-AUTO-PROGRAM-ESCAPE-001','2026-06-18','TEST-Centro','TEST: sesión ficticia 10.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":4,"opportunities":20,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":8,"opportunities":20,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-18T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-011','TEST-AUTO-PROGRAM-ESCAPE-001','2026-06-24','TEST-Escuela','TEST: sesión ficticia 11.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":4,"opportunities":19,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":9,"opportunities":19,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-24T16:00:00.000Z'),
('TEST-AUTO-SESSION-ESC-012','TEST-AUTO-PROGRAM-ESCAPE-001','2026-07-01','TEST-Casa','TEST: sesión agregada después de la configuración para validar actualización automática.','closed','[{"targetId":"TEST-AUTO-TARGET-ESCAPE-001","sampled":true,"value":3,"opportunities":20,"note":"TEST-Nueva sesión","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-BREAK-001","sampled":true,"value":10,"opportunities":20,"note":"TEST-Nueva sesión","stateAtSession":"acquisition"}]','[]','2026-07-01T16:00:00.000Z');
--> statement-breakpoint
INSERT OR IGNORE INTO `intervention_sessions` (`id`,`program_id`,`session_date`,`context`,`notes`,`status`,`results`,`transitions`,`closed_at`) VALUES
('TEST-AUTO-SESSION-FCT-001','TEST-AUTO-PROGRAM-FCT-001','2026-05-05','TEST-Centro','TEST: sesión ficticia 1.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":20,"opportunities":10,"note":"TEST-LB","stateAtSession":"baseline"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":70,"opportunities":10,"note":"TEST-LB","stateAtSession":"baseline"}]','[]','2026-05-05T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-002','TEST-AUTO-PROGRAM-FCT-001','2026-05-09','TEST-Escuela','TEST: sesión ficticia 2.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":25,"opportunities":12,"note":"TEST-LB","stateAtSession":"baseline"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":67,"opportunities":12,"note":"TEST-LB","stateAtSession":"baseline"}]','[]','2026-05-09T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-003','TEST-AUTO-PROGRAM-FCT-001','2026-05-13','TEST-Casa','TEST: sesión ficticia 3.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":20,"opportunities":10,"note":"TEST-LB","stateAtSession":"baseline"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":70,"opportunities":10,"note":"TEST-LB","stateAtSession":"baseline"}]','[]','2026-05-13T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-004','TEST-AUTO-PROGRAM-FCT-001','2026-05-17','TEST-Centro','TEST: sesión ficticia 4.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":30,"opportunities":10,"note":"TEST-LB","stateAtSession":"baseline"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":60,"opportunities":10,"note":"TEST-LB","stateAtSession":"baseline"}]','[]','2026-05-17T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-005','TEST-AUTO-PROGRAM-FCT-001','2026-05-24','TEST-Escuela','TEST: inicio ficticio de intervención.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":40,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":50,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","code":"FCT-01","targetName":"Solicitud independiente","from":"baseline","to":"acquisition","reason":"TEST: cambio sintético de fase"}]','2026-05-24T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-006','TEST-AUTO-PROGRAM-FCT-001','2026-05-28','TEST-Casa','TEST: sesión ficticia 6.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":50,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":40,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-05-28T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-007','TEST-AUTO-PROGRAM-FCT-001','2026-06-03','TEST-Centro','TEST: sesión ficticia 7.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":60,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":false,"value":null,"opportunities":0,"note":"TEST-No muestreado","stateAtSession":"acquisition"}]','[]','2026-06-03T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-008','TEST-AUTO-PROGRAM-FCT-001','2026-06-08','TEST-Escuela','TEST: sesión ficticia 8.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":65,"opportunities":12,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":33,"opportunities":12,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-08T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-009','TEST-AUTO-PROGRAM-FCT-001','2026-06-15','TEST-Casa','TEST: sesión ficticia 9.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":70,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":30,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-15T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-010','TEST-AUTO-PROGRAM-FCT-001','2026-06-19','TEST-Centro','TEST: sesión ficticia 10.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":80,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":20,"opportunities":10,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-19T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-011','TEST-AUTO-PROGRAM-FCT-001','2026-06-25','TEST-Escuela','TEST: sesión ficticia 11.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":85,"opportunities":12,"note":"TEST-Intervención","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":17,"opportunities":12,"note":"TEST-Intervención","stateAtSession":"acquisition"}]','[]','2026-06-25T16:00:00.000Z'),
('TEST-AUTO-SESSION-FCT-012','TEST-AUTO-PROGRAM-FCT-001','2026-07-02','TEST-Casa','TEST: sesión agregada después de la configuración para validar actualización automática.','closed','[{"targetId":"TEST-AUTO-TARGET-FCT-IND-001","sampled":true,"value":90,"opportunities":10,"note":"TEST-Nueva sesión","stateAtSession":"acquisition"},{"targetId":"TEST-AUTO-TARGET-FCT-PROMPT-001","sampled":true,"value":10,"opportunities":10,"note":"TEST-Nueva sesión","stateAtSession":"acquisition"}]','[]','2026-07-02T16:00:00.000Z');
--> statement-breakpoint
INSERT OR IGNORE INTO `analytic_graphs` (`id`,`owner_account_id`,`profile_id`,`linked_program_id`,`title`,`objective`,`graph_type`,`design_type`,`measurement`,`x_axis_label`,`y_axis_label`,`linked_cycle_id`,`status`,`points`,`phases`,`config`) VALUES
('TEST-AUTO-GRAPH-ESCAPE-001','TEST-DIRECTOR-001','TEST-AUTO-GRAPH-CLIENT-001','TEST-AUTO-PROGRAM-ESCAPE-001','TEST-AUTO · Escape · Línea base vs intervención','TEST: configuración automática ficticia conectada a sesiones de frecuencia.','line','AB','Frecuencia','Fechas de sesión','episodios',NULL,'active','[]','[{"id":"TEST-AUTO-PHASE-ESC-001","afterIndex":4,"beforeLabel":"Línea base","afterLabel":"Intervención","boundaryDate":"2026-05-23"}]','{"yMin":0,"yMax":null,"showGrid":true,"showMean":false,"showTrend":true,"connectPoints":true,"showPoints":true,"showLegend":true,"showValues":true,"dataSource":"sessions","sourceTargetIds":["TEST-AUTO-TARGET-ESCAPE-001","TEST-AUTO-TARGET-BREAK-001"],"dateFrom":"","dateTo":"","visualAnalysis":{"level":"TEST: datos sintéticos","trend":"TEST: descenso de escape y ascenso de conducta alternativa","variability":"TEST: variabilidad controlada","immediacy":"TEST: revisar transición","overlap":"TEST: no clínico","consistency":"TEST: patrón reproducible","decision":"TEST: validar únicamente la plataforma","nextReview":"2026-09-01"}}'),
('TEST-AUTO-GRAPH-FCT-001','TEST-DIRECTOR-001','TEST-AUTO-GRAPH-CLIENT-001','TEST-AUTO-PROGRAM-FCT-001','TEST-AUTO · Comunicación funcional · Progreso','TEST: configuración automática ficticia conectada a sesiones de porcentaje.','line','AB','Porcentaje','Fechas de sesión','%',NULL,'active','[]','[{"id":"TEST-AUTO-PHASE-FCT-001","afterIndex":4,"beforeLabel":"Línea base","afterLabel":"Intervención","boundaryDate":"2026-05-24"}]','{"yMin":0,"yMax":100,"showGrid":true,"showMean":false,"showTrend":true,"connectPoints":true,"showPoints":true,"showLegend":true,"showValues":true,"dataSource":"sessions","sourceTargetIds":["TEST-AUTO-TARGET-FCT-IND-001","TEST-AUTO-TARGET-FCT-PROMPT-001"],"dateFrom":"","dateTo":"","visualAnalysis":{"level":"TEST: datos sintéticos","trend":"TEST: adquisición progresiva","variability":"TEST: dato faltante intencional","immediacy":"TEST: revisar transición","overlap":"TEST: no clínico","consistency":"TEST: patrón reproducible","decision":"TEST: validar únicamente la plataforma","nextReview":"2026-09-01"}}');
--> statement-breakpoint
INSERT OR IGNORE INTO `graph_history` (`id`,`graph_id`,`action`,`summary`,`details`) VALUES
('TEST-AUTO-GRAPH-HISTORY-ESC-001','TEST-AUTO-GRAPH-ESCAPE-001','created','TEST: configuración automática creada','TEST: fuente sessions · 2 targets · AB'),
('TEST-AUTO-GRAPH-HISTORY-FCT-001','TEST-AUTO-GRAPH-FCT-001','created','TEST: configuración automática creada','TEST: fuente sessions · 2 targets · AB');
